package com.example_demo.model;

import java.util.Objects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ActionResultDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Boolean Result")
	private java.lang.Boolean boolResult;

	public ActionResultDO() {
	}

	public java.lang.Boolean getBoolResult() {
		return this.boolResult;
	}

	public void setBoolResult(java.lang.Boolean boolResult) {
		this.boolResult = boolResult;
	}

	public ActionResultDO(java.lang.Boolean boolResult) {
		this.boolResult = boolResult;
	}

	@Override
	public String toString() {
		return Objects.isNull(boolResult)?" ":boolResult.toString();
	}
}