package com.example_demo.model;

import java.util.Objects;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ActionResultDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("Boolean Result")
    private java.lang.Boolean boolResult;

    @org.kie.api.definition.type.Label(value = "String")
    private java.lang.String str;

    public ActionResultDO() {
    }

    public ActionResultDO(java.lang.Boolean boolResult, java.lang.String str) {
        this.boolResult = boolResult;
        this.str = str;
    }

    public java.lang.Boolean getBoolResult() {
        return this.boolResult;
    }

    public void setBoolResult(java.lang.Boolean boolResult) {
        this.boolResult = boolResult;
    }

    @Override
    public String toString() {
        return Objects.isNull(boolResult) ? " " : boolResult.toString();
    }

    public java.lang.String getStr() {
        return this.str;
    }

    public void setStr(java.lang.String str) {
        this.str = str;
    }

    public static Boolean and(Boolean bool, Boolean bool1) {
        Supplier<Boolean> supplier = () -> bool && bool1;
        return operation(bool, bool1, supplier);
    }

    public static Boolean or(Boolean bool, Boolean bool1) {
        Supplier<Boolean> supplier = () -> bool || bool1;
        return operation(bool, bool1, supplier);

    }

    public static Boolean operation(Boolean bool, Boolean bool1, Supplier<Boolean> booleanSupplier) {
        if (Objects.isNull(bool) && Objects.isNull(bool1)) {
            return null;
        }

        if (Objects.isNull(bool) && Objects.nonNull(bool1)) {
            return bool1;
        }

        if (Objects.nonNull(bool) && Objects.isNull(bool1)) {
            return bool;
        }
        return booleanSupplier.get();
    }
}