package com.example_demo.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerAttachmentDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CustomerAttachmentDO() {
    }




}