package com.example_demo.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Customer ID")
	private java.lang.Long customerId;
	@org.kie.api.definition.type.Label("Customer Name")
	private java.lang.String customerName;
	@org.kie.api.definition.type.Label("Customer Type")
	private java.lang.Integer customerType;
	@org.kie.api.definition.type.Label("Create Time")
	private java.time.LocalDateTime createTime;
	@org.kie.api.definition.type.Label("Update Time")
	private java.time.LocalDateTime updateTime;

	@org.kie.api.definition.type.Label("Login Account")
	private java.lang.String loginAccount;

	@org.kie.api.definition.type.Label("Login Password")
	private java.lang.String loginPassword;

	@org.kie.api.definition.type.Label("Enabled")
	private java.lang.Boolean enabled;

	@org.kie.api.definition.type.Label("Status")
	private java.lang.Integer status;

	@org.kie.api.definition.type.Label(value = "Bind Account List")
	private java.util.List<com.example_demo.model.CustomerBindAccountDO> accountList;

	public CustomerDO() {
	}

	public java.lang.Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.Long customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(java.lang.String customerName) {
		this.customerName = customerName;
	}

	public java.lang.Integer getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(java.lang.Integer customerType) {
		this.customerType = customerType;
	}

	public java.time.LocalDateTime getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.time.LocalDateTime createTime) {
		this.createTime = createTime;
	}

	public java.time.LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(java.time.LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public java.lang.String getLoginAccount() {
		return this.loginAccount;
	}

	public void setLoginAccount(java.lang.String loginAccount) {
		this.loginAccount = loginAccount;
	}

	public java.lang.String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(java.lang.String loginPassword) {
		this.loginPassword = loginPassword;
	}

	public java.lang.Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(java.lang.Boolean enabled) {
		this.enabled = enabled;
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}

	public java.util.List<com.example_demo.model.CustomerBindAccountDO> getAccountList() {
		return this.accountList;
	}

	public void setAccountList(
			java.util.List<com.example_demo.model.CustomerBindAccountDO> accountList) {
		this.accountList = accountList;
	}

	public CustomerDO(
			java.lang.Long customerId,
			java.lang.String customerName,
			java.lang.Integer customerType,
			java.time.LocalDateTime createTime,
			java.time.LocalDateTime updateTime,
			java.lang.String loginAccount,
			java.lang.String loginPassword,
			java.lang.Boolean enabled,
			java.lang.Integer status,
			java.util.List<com.example_demo.model.CustomerBindAccountDO> accountList) {
		this.customerId = customerId;
		this.customerName = customerName;
		this.customerType = customerType;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.loginAccount = loginAccount;
		this.loginPassword = loginPassword;
		this.enabled = enabled;
		this.status = status;
		this.accountList = accountList;
	}

}