package com.example_demo.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerIdInfoDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Id Number")
	private java.lang.String idNumber;
	@org.kie.api.definition.type.Label("Id Type")
	private java.lang.String idType;
	@org.kie.api.definition.type.Label("Validate")
	private java.lang.Boolean validate;
	@org.kie.api.definition.type.Label("Effective start time")
	private java.time.LocalDateTime effectiveStartTime;
	@org.kie.api.definition.type.Label("Effective end time")
	private java.time.LocalDateTime effectiveEndTime;

	@org.kie.api.definition.type.Label("customerID")
	private java.lang.Long customerId;

	@org.kie.api.definition.type.Label("Create Time")
	private java.time.LocalDateTime createTime;

	@org.kie.api.definition.type.Label("Update Time")
	private java.time.LocalDateTime updateTime;

	public CustomerIdInfoDO() {
	}

	public java.lang.String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(java.lang.String idNumber) {
		this.idNumber = idNumber;
	}

	public java.lang.String getIdType() {
		return this.idType;
	}

	public void setIdType(java.lang.String idType) {
		this.idType = idType;
	}

	public java.lang.Boolean getValidate() {
		return this.validate;
	}

	public void setValidate(java.lang.Boolean validate) {
		this.validate = validate;
	}

	public java.time.LocalDateTime getEffectiveStartTime() {
		return this.effectiveStartTime;
	}

	public void setEffectiveStartTime(java.time.LocalDateTime effectiveStartTime) {
		this.effectiveStartTime = effectiveStartTime;
	}

	public java.time.LocalDateTime getEffectiveEndTime() {
		return this.effectiveEndTime;
	}

	public void setEffectiveEndTime(java.time.LocalDateTime effectiveEndTime) {
		this.effectiveEndTime = effectiveEndTime;
	}

	public java.lang.Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.Long customerId) {
		this.customerId = customerId;
	}

	public java.time.LocalDateTime getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.time.LocalDateTime createTime) {
		this.createTime = createTime;
	}

	public java.time.LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(java.time.LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public CustomerIdInfoDO(java.lang.String idNumber, java.lang.String idType,
			java.lang.Boolean validate,
			java.time.LocalDateTime effectiveStartTime,
			java.time.LocalDateTime effectiveEndTime,
			java.lang.Long customerId, java.time.LocalDateTime createTime,
			java.time.LocalDateTime updateTime) {
		this.idNumber = idNumber;
		this.idType = idType;
		this.validate = validate;
		this.effectiveStartTime = effectiveStartTime;
		this.effectiveEndTime = effectiveEndTime;
		this.customerId = customerId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

}