package com.example_demo.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerBindAccountDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Customer ID")
	private java.lang.Long customerId;
	@org.kie.api.definition.type.Label("Bind Account")
	private java.lang.String bindAccount;
	@org.kie.api.definition.type.Label("Bind Account Type")
	private java.lang.String bindAccountType;
	@org.kie.api.definition.type.Label("validation")
	private java.lang.Boolean validation;
	@org.kie.api.definition.type.Label("Create Time")
	private java.time.LocalDateTime createTime;
	@org.kie.api.definition.type.Label("Update Time")
	private java.time.LocalDateTime updateTime;

	public CustomerBindAccountDO() {
	}

	public java.lang.Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.Long customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getBindAccount() {
		return this.bindAccount;
	}

	public void setBindAccount(java.lang.String bindAccount) {
		this.bindAccount = bindAccount;
	}

	public java.lang.String getBindAccountType() {
		return this.bindAccountType;
	}

	public void setBindAccountType(java.lang.String bindAccountType) {
		this.bindAccountType = bindAccountType;
	}

	public java.lang.Boolean getValidation() {
		return this.validation;
	}

	public void setValidation(java.lang.Boolean validation) {
		this.validation = validation;
	}

	public java.time.LocalDateTime getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.time.LocalDateTime createTime) {
		this.createTime = createTime;
	}

	public java.time.LocalDateTime getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(java.time.LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public CustomerBindAccountDO(java.lang.Long customerId,
			java.lang.String bindAccount, java.lang.String bindAccountType,
			java.lang.Boolean validation, java.time.LocalDateTime createTime,
			java.time.LocalDateTime updateTime) {
		this.customerId = customerId;
		this.bindAccount = bindAccount;
		this.bindAccountType = bindAccountType;
		this.validation = validation;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

}