package com.example_demo.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LogDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String msg;

	public LogDO() {
	}

	public java.lang.String getMsg() {
		return this.msg;
	}

	public void setMsg(java.lang.String msg) {
		this.msg = msg;
	}

	public LogDO(java.lang.String msg) {
		this.msg = msg;
	}

}